# Turn templates/*.mustache into a generated C++ header of string constants.
#
# The templates are compiled into the binary rather than read from disk at
# runtime on purpose. The pages these templates render are the ones that ask
# for the vault login and master password, and the setup page is what the
# operator checks a certificate fingerprint against. A templates directory read
# at runtime would let anyone who can write to it rewrite that page -- drop the
# fingerprint, add a field, post the password elsewhere -- without touching the
# binary. Embedding keeps the pages as trustworthy as the executable itself.
#
# Usage:
#   cmake -DOUTPUT=<header> -DTEMPLATES=<;-separated .mustache files>
#         -P scripts/embed_templates.cmake

if(NOT DEFINED OUTPUT OR NOT DEFINED TEMPLATES)
    message(FATAL_ERROR "embed_templates.cmake needs -DOUTPUT and -DTEMPLATES")
endif()

set(DELIMITER "MUSTACHE")

set(BODY "")
foreach(TEMPLATE IN LISTS TEMPLATES)
    get_filename_component(STEM "${TEMPLATE}" NAME_WE)
    get_filename_component(FILENAME "${TEMPLATE}" NAME)

    # unlock_page -> kUnlockPage
    string(REPLACE "_" ";" WORDS "${STEM}")
    set(CONSTANT "k")
    foreach(WORD IN LISTS WORDS)
        string(SUBSTRING "${WORD}" 0 1 HEAD)
        string(TOUPPER "${HEAD}" HEAD)
        string(SUBSTRING "${WORD}" 1 -1 TAIL)
        string(APPEND CONSTANT "${HEAD}${TAIL}")
    endforeach()

    file(READ "${TEMPLATE}" CONTENT)
    # A raw string ends at the delimiter, so the delimiter must not occur in
    # the template. Fail the build rather than emit a header that will not
    # compile, or worse, one that truncates a page.
    if(CONTENT MATCHES "\\)${DELIMITER}\"")
        message(FATAL_ERROR
            "${FILENAME} contains the raw string delimiter )${DELIMITER}\"")
    endif()

    string(APPEND BODY "/// From templates/${FILENAME}.\n")
    string(APPEND BODY
        "inline constexpr std::string_view ${CONSTANT} =\n")
    string(APPEND BODY "    R\"${DELIMITER}(${CONTENT})${DELIMITER}\";\n\n")
endforeach()

set(HEADER "//===----------------------------------------------------------------------===//
/// \\file
/// The HTML templates, embedded at build time.
///
/// Generated by scripts/embed_templates.cmake from templates/*.mustache.
/// Do not edit: edit the template and rebuild.
//===----------------------------------------------------------------------===//

#ifndef ALFIE_TEMPLATES_H
#define ALFIE_TEMPLATES_H

#include <string_view>

namespace alfie::tmpl {

${BODY}} // namespace alfie::tmpl

#endif // ALFIE_TEMPLATES_H
")

# Only rewrite when the contents change, so an unrelated reconfigure does not
# force every dependent translation unit to rebuild.
if(EXISTS "${OUTPUT}")
    file(READ "${OUTPUT}" EXISTING)
    if(EXISTING STREQUAL HEADER)
        # Nothing changed, so leave the contents alone and only mark it fresh:
        # rewriting would rebuild every translation unit that includes it.
        file(TOUCH "${OUTPUT}")
        return()
    endif()
endif()
file(WRITE "${OUTPUT}" "${HEADER}")
